services:
  - type: web
    name: comic-panel-description-generator
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_SECRET_KEY
        generateValue: true
      # API Keys for text generation - set these in the Render.com dashboard
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GROK_API_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: BRAVE_API_KEY
        sync: false
